language: php

sudo: false

notifications:
  email:
    on_success: never

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2
  - 7.3

env:
  matrix:
  - TESTBENCH=3.4.* PHPUNIT=~5.7.21
  - TESTBENCH=3.5.* PHPUNIT=~6.0
  - TESTBENCH=3.6.* PHPUNIT=^7.0
  - TESTBENCH=3.7.* PHPUNIT=^7.0
  - TESTBENCH=3.8.* PHPUNIT=^7.5
  - TESTBENCH=3.9.* PHPUNIT=^7.5
  - TESTBENCH=^4.0  PHPUNIT=^8.0

before_install:
  - composer self-update --stable --no-interaction
  - composer require orchestra/testbench:$TESTBENCH phpunit/phpunit:$PHPUNIT --no-update --no-interaction --dev

install:
  - travis_retry composer update --no-suggest --no-interaction
  - composer info

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
